using System.Text;

namespace SoloJs.Compiler;

public sealed class JsEmitter
{
    public string Emit(SoloJsProgram program, string? title = null)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by SoloJS — SoloGem Solo5");
        if (!string.IsNullOrWhiteSpace(title))
            sb.Append("// ").AppendLine(title);
        sb.AppendLine(Runtime);
        sb.AppendLine();
        EmitBlock(sb, program.Body, 0, new HashSet<string>(StringComparer.Ordinal));
        return sb.ToString();
    }

    private static void EmitBlock(StringBuilder sb, List<SoloJsNode> nodes, int depth, HashSet<string> declared)
    {
        var pad = new string(' ', depth * 2);
        foreach (var node in nodes)
            EmitNode(sb, node, depth, pad, declared);
    }

    private static void EmitNode(StringBuilder sb, SoloJsNode node, int depth, string pad, HashSet<string> declared)
    {
        switch (node)
        {
            case SoloJsComment c:
                sb.Append(pad).Append("// ").AppendLine(c.Text);
                break;

            case SoloJsFn fn:
                sb.Append(pad).Append("function ").Append(fn.Name).Append('(')
                    .Append(string.Join(", ", fn.Params)).AppendLine(") {");
                var fnScope = new HashSet<string>(fn.Params, StringComparer.Ordinal);
                EmitBlock(sb, fn.Body, depth + 1, fnScope);
                sb.Append(pad).AppendLine("}");
                sb.AppendLine();
                break;

            case SoloJsIf iff:
                sb.Append(pad).Append("if (").Append(iff.Condition).AppendLine(") {");
                EmitBlock(sb, iff.ThenBody, depth + 1, declared);
                sb.Append(pad).Append('}');
                if (iff.ElseBody.Count > 0)
                {
                    if (iff.ElseBody is [SoloJsIf only])
                    {
                        sb.Append(" else ");
                        EmitIfContinue(sb, only, depth, declared);
                    }
                    else
                    {
                        sb.AppendLine(" else {");
                        EmitBlock(sb, iff.ElseBody, depth + 1, declared);
                        sb.Append(pad).AppendLine("}");
                    }
                }
                else
                {
                    sb.AppendLine();
                }
                break;

            case SoloJsWhile wh:
                sb.Append(pad).Append("while (").Append(wh.Condition).AppendLine(") {");
                EmitBlock(sb, wh.Body, depth + 1, declared);
                sb.Append(pad).AppendLine("}");
                break;

            case SoloJsForRange fr:
                sb.Append(pad).Append("for (let ").Append(fr.Variable).Append(" = ").Append(fr.Start)
                    .Append("; ").Append(fr.Variable).Append(" < ").Append(fr.End)
                    .Append("; ").Append(fr.Variable).AppendLine("++) {");
                var rangeScope = new HashSet<string>(declared, StringComparer.Ordinal) { fr.Variable };
                EmitBlock(sb, fr.Body, depth + 1, rangeScope);
                sb.Append(pad).AppendLine("}");
                break;

            case SoloJsForEach fe:
                sb.Append(pad).Append("for (const ").Append(fe.Variable).Append(" of ")
                    .Append(fe.Iterable).AppendLine(") {");
                var eachScope = new HashSet<string>(declared, StringComparer.Ordinal) { fe.Variable };
                EmitBlock(sb, fe.Body, depth + 1, eachScope);
                sb.Append(pad).AppendLine("}");
                break;

            case SoloJsWhenReady wr:
                sb.Append(pad).AppendLine("document.addEventListener(\"DOMContentLoaded\", () => {");
                EmitBlock(sb, wr.Body, depth + 1, declared);
                sb.Append(pad).AppendLine("});");
                sb.AppendLine();
                break;

            case SoloJsOn on:
                sb.Append(pad).Append("solo.on(").Append(JsString(on.Selector)).Append(", ")
                    .Append(JsString(on.EventName)).AppendLine(", () => {");
                EmitBlock(sb, on.Body, depth + 1, declared);
                sb.Append(pad).AppendLine("});");
                break;

            case SoloJsFetch fetch:
            {
                var urlExpr = fetch.Url.StartsWith('"') || fetch.Url.StartsWith('\'') || fetch.Url.StartsWith('`')
                    ? fetch.Url
                    : JsString(fetch.Url);
                sb.Append(pad).Append("solo.fetch(").Append(urlExpr).AppendLine(").then(async (__res) => {");
                sb.Append(pad).AppendLine("  const __data = await __res.text();");
                if (!string.IsNullOrWhiteSpace(fetch.Into))
                {
                    if (declared.Add(fetch.Into!))
                        sb.Append(pad).Append("  let ").Append(fetch.Into).AppendLine(" = __data;");
                    else
                        sb.Append(pad).Append("  ").Append(fetch.Into).AppendLine(" = __data;");
                }
                EmitBlock(sb, fetch.ThenBody, depth + 1, declared);
                sb.Append(pad).Append("})");
                if (fetch.CatchBody.Count > 0)
                {
                    sb.AppendLine(".catch((__err) => {");
                    EmitBlock(sb, fetch.CatchBody, depth + 1, declared);
                    sb.Append(pad).AppendLine("});");
                }
                else
                {
                    sb.AppendLine(";");
                }
                break;
            }

            case SoloJsAfter after:
                sb.Append(pad).Append("solo.after(").Append(after.DelayMs).AppendLine(", () => {");
                EmitBlock(sb, after.Body, depth + 1, declared);
                sb.Append(pad).AppendLine("});");
                break;

            case SoloJsEvery every:
                sb.Append(pad).Append("solo.every(").Append(every.IntervalMs).AppendLine(", () => {");
                EmitBlock(sb, every.Body, depth + 1, declared);
                sb.Append(pad).AppendLine("});");
                break;

            case SoloJsSet set:
                sb.Append(pad).Append("solo.set(").Append(JsString(set.Selector)).Append(", ")
                    .Append(JsString(set.Property)).Append(", ").Append(set.Value).AppendLine(");");
                break;

            case SoloJsPrint p:
                sb.Append(pad).Append("console.log(").Append(p.Args).AppendLine(");");
                break;

            case SoloJsReturn r:
                sb.Append(pad).Append("return");
                if (r.Value is not null)
                    sb.Append(' ').Append(r.Value);
                sb.AppendLine(";");
                break;

            case SoloJsAssign a:
                if (a.Keyword is not null)
                {
                    declared.Add(a.Name);
                    sb.Append(pad).Append(a.Keyword).Append(' ').Append(a.Name).Append(" = ").Append(a.Value).AppendLine(";");
                }
                else if (declared.Add(a.Name))
                {
                    sb.Append(pad).Append("let ").Append(a.Name).Append(" = ").Append(a.Value).AppendLine(";");
                }
                else
                {
                    sb.Append(pad).Append(a.Name).Append(" = ").Append(a.Value).AppendLine(";");
                }
                break;

            case SoloJsExpr e:
                sb.Append(pad).Append(e.Code).AppendLine(";");
                break;

            case SoloJsRaw raw:
                sb.Append(pad).AppendLine(raw.Code);
                break;
        }
    }

    private static void EmitIfContinue(StringBuilder sb, SoloJsIf iff, int depth, HashSet<string> declared)
    {
        var pad = new string(' ', depth * 2);
        sb.Append("if (").Append(iff.Condition).AppendLine(") {");
        EmitBlock(sb, iff.ThenBody, depth + 1, declared);
        sb.Append(pad).Append('}');
        if (iff.ElseBody.Count > 0)
        {
            if (iff.ElseBody is [SoloJsIf only])
            {
                sb.Append(" else ");
                EmitIfContinue(sb, only, depth, declared);
            }
            else
            {
                sb.AppendLine(" else {");
                EmitBlock(sb, iff.ElseBody, depth + 1, declared);
                sb.Append(pad).AppendLine("}");
            }
        }
        else sb.AppendLine();
    }

    private static string JsString(string s) =>
        "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private const string Runtime = """
const solo = {
  $(sel) {
    return document.querySelector(sel);
  },
  on(sel, eventName, handler) {
    const el = this.$(sel);
    if (!el) { console.warn("SoloJS: no element for", sel); return; }
    el.addEventListener(eventName, handler);
  },
  set(sel, prop, value) {
    const el = this.$(sel);
    if (!el) { console.warn("SoloJS: no element for", sel); return; }
    if (prop === "text") el.textContent = value;
    else if (prop === "html") el.innerHTML = value;
    else if (prop === "value") el.value = value;
    else if (prop === "class") el.className = value;
    else el.setAttribute(prop, value);
  },
  fetch(url) {
    return fetch(url);
  },
  after(ms, handler) {
    return setTimeout(handler, Number(ms));
  },
  every(ms, handler) {
    return setInterval(handler, Number(ms));
  }
};
""";
}
