using System.Text;

namespace SoloJs.Compiler;

public sealed class JsEmitter
{
    public string Emit(SoloJsProgram program, string? title = null)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by SoloJS — SoloGem Solo5");
        if (!string.IsNullOrWhiteSpace(title))
            sb.Append("// ").AppendLine(title);

        if (program.UsesReact)
        {
            sb.AppendLine(ReactPreamble);
            sb.AppendLine();
        }

        sb.AppendLine(Runtime);
        sb.AppendLine();
        EmitBlock(sb, program.Body, 0, new HashSet<string>(StringComparer.Ordinal), stateVars: null);
        return sb.ToString();
    }

    private static void EmitBlock(
        StringBuilder sb,
        List<SoloJsNode> nodes,
        int depth,
        HashSet<string> declared,
        HashSet<string>? stateVars)
    {
        var pad = new string(' ', depth * 2);
        foreach (var node in nodes)
            EmitNode(sb, node, depth, pad, declared, stateVars);
    }

    private static void EmitNode(
        StringBuilder sb,
        SoloJsNode node,
        int depth,
        string pad,
        HashSet<string> declared,
        HashSet<string>? stateVars)
    {
        switch (node)
        {
            case SoloJsComment c:
                sb.Append(pad).Append("// ").AppendLine(c.Text);
                break;

            case SoloJsReactEnable:
                sb.Append(pad).AppendLine("// react enabled");
                break;

            case SoloJsComponent comp:
                EmitComponent(sb, comp, depth, pad);
                break;

            case SoloJsMount mount:
                sb.Append(pad).Append("solo.react.mount(")
                    .Append(mount.Component).Append(", ")
                    .Append(JsString(mount.Selector));
                if (mount.Props.Count > 0)
                {
                    sb.Append(", { ");
                    sb.Append(string.Join(", ", mount.Props.Select(kv =>
                        $"{kv.Key}: {PropValue(kv.Value)}")));
                    sb.Append(" }");
                }
                sb.AppendLine(");");
                break;

            case SoloJsFn fn:
                sb.Append(pad).Append("function ").Append(fn.Name).Append('(')
                    .Append(string.Join(", ", fn.Params)).AppendLine(") {");
                var fnScope = new HashSet<string>(fn.Params, StringComparer.Ordinal);
                EmitBlock(sb, fn.Body, depth + 1, fnScope, stateVars);
                sb.Append(pad).AppendLine("}");
                sb.AppendLine();
                break;

            case SoloJsIf iff:
                sb.Append(pad).Append("if (").Append(RewriteStateExpr(iff.Condition, stateVars)).AppendLine(") {");
                EmitBlock(sb, iff.ThenBody, depth + 1, declared, stateVars);
                sb.Append(pad).Append('}');
                if (iff.ElseBody.Count > 0)
                {
                    if (iff.ElseBody is [SoloJsIf only])
                    {
                        sb.Append(" else ");
                        EmitIfContinue(sb, only, depth, declared, stateVars);
                    }
                    else
                    {
                        sb.AppendLine(" else {");
                        EmitBlock(sb, iff.ElseBody, depth + 1, declared, stateVars);
                        sb.Append(pad).AppendLine("}");
                    }
                }
                else sb.AppendLine();
                break;

            case SoloJsWhile wh:
                sb.Append(pad).Append("while (").Append(RewriteStateExpr(wh.Condition, stateVars)).AppendLine(") {");
                EmitBlock(sb, wh.Body, depth + 1, declared, stateVars);
                sb.Append(pad).AppendLine("}");
                break;

            case SoloJsForRange fr:
                sb.Append(pad).Append("for (let ").Append(fr.Variable).Append(" = ").Append(fr.Start)
                    .Append("; ").Append(fr.Variable).Append(" < ").Append(fr.End)
                    .Append("; ").Append(fr.Variable).AppendLine("++) {");
                var rangeScope = new HashSet<string>(declared, StringComparer.Ordinal) { fr.Variable };
                EmitBlock(sb, fr.Body, depth + 1, rangeScope, stateVars);
                sb.Append(pad).AppendLine("}");
                break;

            case SoloJsForEach fe:
                sb.Append(pad).Append("for (const ").Append(fe.Variable).Append(" of ")
                    .Append(fe.Iterable).AppendLine(") {");
                var eachScope = new HashSet<string>(declared, StringComparer.Ordinal) { fe.Variable };
                EmitBlock(sb, fe.Body, depth + 1, eachScope, stateVars);
                sb.Append(pad).AppendLine("}");
                break;

            case SoloJsWhenReady wr:
                sb.Append(pad).AppendLine("document.addEventListener(\"DOMContentLoaded\", () => {");
                EmitBlock(sb, wr.Body, depth + 1, declared, stateVars);
                sb.Append(pad).AppendLine("});");
                sb.AppendLine();
                break;

            case SoloJsOn on:
                sb.Append(pad).Append("solo.on(").Append(JsString(on.Selector)).Append(", ")
                    .Append(JsString(on.EventName)).AppendLine(", () => {");
                EmitBlock(sb, on.Body, depth + 1, declared, stateVars);
                sb.Append(pad).AppendLine("});");
                break;

            case SoloJsFetch fetch:
            {
                var urlExpr = fetch.Url.StartsWith('"') || fetch.Url.StartsWith('\'') || fetch.Url.StartsWith('`')
                    ? fetch.Url
                    : JsString(fetch.Url);
                sb.Append(pad).Append("solo.fetch(").Append(urlExpr).AppendLine(").then(async (__res) => {");
                sb.Append(pad).AppendLine("  const __data = await __res.text();");
                if (!string.IsNullOrWhiteSpace(fetch.Into))
                {
                    if (declared.Add(fetch.Into!))
                        sb.Append(pad).Append("  let ").Append(fetch.Into).AppendLine(" = __data;");
                    else
                        sb.Append(pad).Append("  ").Append(fetch.Into).AppendLine(" = __data;");
                }
                EmitBlock(sb, fetch.ThenBody, depth + 1, declared, stateVars);
                sb.Append(pad).Append("})");
                if (fetch.CatchBody.Count > 0)
                {
                    sb.AppendLine(".catch((__err) => {");
                    EmitBlock(sb, fetch.CatchBody, depth + 1, declared, stateVars);
                    sb.Append(pad).AppendLine("});");
                }
                else sb.AppendLine(";");
                break;
            }

            case SoloJsAfter after:
                sb.Append(pad).Append("solo.after(").Append(after.DelayMs).AppendLine(", () => {");
                EmitBlock(sb, after.Body, depth + 1, declared, stateVars);
                sb.Append(pad).AppendLine("});");
                break;

            case SoloJsEvery every:
                sb.Append(pad).Append("solo.every(").Append(every.IntervalMs).AppendLine(", () => {");
                EmitBlock(sb, every.Body, depth + 1, declared, stateVars);
                sb.Append(pad).AppendLine("});");
                break;

            case SoloJsSet set:
                sb.Append(pad).Append("solo.set(").Append(JsString(set.Selector)).Append(", ")
                    .Append(JsString(set.Property)).Append(", ").Append(set.Value).AppendLine(");");
                break;

            case SoloJsPrint p:
                sb.Append(pad).Append("console.log(").Append(p.Args).AppendLine(");");
                break;

            case SoloJsReturn r:
                sb.Append(pad).Append("return");
                if (r.Value is not null)
                    sb.Append(' ').Append(RewriteStateExpr(r.Value, stateVars));
                sb.AppendLine(";");
                break;

            case SoloJsAssign a:
                if (stateVars is not null && stateVars.Contains(a.Name) && a.Keyword is null)
                {
                    sb.Append(pad).Append(SetterName(a.Name)).Append('(')
                        .Append(RewriteStateExpr(a.Value, stateVars)).AppendLine(");");
                    break;
                }

                if (a.Keyword is not null)
                {
                    declared.Add(a.Name);
                    sb.Append(pad).Append(a.Keyword).Append(' ').Append(a.Name).Append(" = ")
                        .Append(RewriteStateExpr(a.Value, stateVars)).AppendLine(";");
                }
                else if (declared.Add(a.Name))
                {
                    sb.Append(pad).Append("let ").Append(a.Name).Append(" = ")
                        .Append(RewriteStateExpr(a.Value, stateVars)).AppendLine(";");
                }
                else
                {
                    sb.Append(pad).Append(a.Name).Append(" = ")
                        .Append(RewriteStateExpr(a.Value, stateVars)).AppendLine(";");
                }
                break;

            case SoloJsExpr e:
                sb.Append(pad).Append(RewriteStateExpr(e.Code, stateVars)).AppendLine(";");
                break;

            case SoloJsRaw raw:
                sb.Append(pad).AppendLine(raw.Code);
                break;

            case SoloJsState:
            case SoloJsRender:
                // handled inside component
                break;

            case SoloJsElement el:
                sb.Append(pad).Append("return ").Append(EmitElementExpr(el, stateVars)).AppendLine(";");
                break;
        }
    }

    private static void EmitComponent(StringBuilder sb, SoloJsComponent comp, int depth, string pad)
    {
        var states = comp.Body.OfType<SoloJsState>().ToList();
        var stateNames = states.Select(s => s.Name).ToHashSet(StringComparer.Ordinal);
        var render = comp.Body.OfType<SoloJsRender>().LastOrDefault();
        var fns = comp.Body.OfType<SoloJsFn>().ToList();
        var other = comp.Body.Where(n => n is not SoloJsState and not SoloJsRender and not SoloJsFn and not SoloJsComment).ToList();

        sb.Append(pad).Append("function ").Append(comp.Name).AppendLine("(props) {");
        var inner = depth + 1;
        var ipad = new string(' ', inner * 2);

        foreach (var st in states)
        {
            sb.Append(ipad).Append("const [").Append(st.Name).Append(", ").Append(SetterName(st.Name))
                .Append("] = React.useState(").Append(st.Value).AppendLine(");");
        }

        foreach (var fn in fns)
        {
            sb.Append(ipad).Append("function ").Append(fn.Name).Append('(')
                .Append(string.Join(", ", fn.Params)).AppendLine(") {");
            var scope = new HashSet<string>(fn.Params, StringComparer.Ordinal);
            EmitBlock(sb, fn.Body, inner + 1, scope, stateNames);
            sb.Append(ipad).AppendLine("}");
        }

        if (other.Count > 0)
            EmitBlock(sb, other, inner, new HashSet<string>(StringComparer.Ordinal), stateNames);

        if (render is null || render.Children.Count == 0)
        {
            sb.Append(ipad).AppendLine("return null;");
        }
        else if (render.Children.Count == 1 && render.Children[0] is SoloJsElement single)
        {
            sb.Append(ipad).Append("return ").Append(EmitElementExpr(single, stateNames)).AppendLine(";");
        }
        else
        {
            sb.Append(ipad).Append("return React.createElement(React.Fragment, null");
            foreach (var child in render.Children)
            {
                sb.Append(", ");
                if (child is SoloJsElement el)
                    sb.Append(EmitElementExpr(el, stateNames));
                else
                    sb.Append("null");
            }
            sb.AppendLine(");");
        }

        sb.Append(pad).AppendLine("}");
        sb.AppendLine();
    }

    private static string EmitElementExpr(SoloJsElement el, HashSet<string>? stateVars)
    {
        var tagExpr = char.IsUpper(el.Tag[0])
            ? el.Tag
            : JsString(el.Tag);

        var propsParts = new List<string>();
        foreach (var (key, value) in el.Props)
        {
            if (key.StartsWith("on", StringComparison.OrdinalIgnoreCase) && IsIdent(value))
                propsParts.Add($"{key}: {value}");
            else if (value is "true" or "false")
                propsParts.Add($"{key}: {value}");
            else if (key is "className" or "id" or "style" or "type" or "placeholder" or "href" or "src" or "alt")
                propsParts.Add($"{key}: {JsString(value)}");
            else if (IsNumber(value))
                propsParts.Add($"{key}: {value}");
            else if (IsIdent(value) && !key.Equals("className", StringComparison.OrdinalIgnoreCase))
                propsParts.Add($"{key}: {value}");
            else
                propsParts.Add($"{key}: {JsString(value)}");
        }

        var propsExpr = propsParts.Count == 0 ? "null" : "{ " + string.Join(", ", propsParts) + " }";

        var children = new List<string>();
        if (el.TextExpr is not null)
            children.Add(RewriteStateExpr(el.TextExpr, stateVars));
        if (el.Text is not null)
            children.Add(JsString(el.Text));

        foreach (var child in el.Children)
        {
            if (child is SoloJsElement childEl)
                children.Add(EmitElementExpr(childEl, stateVars));
        }

        if (children.Count == 0)
            return $"React.createElement({tagExpr}, {propsExpr})";

        return $"React.createElement({tagExpr}, {propsExpr}, {string.Join(", ", children)})";
    }

    private static void EmitIfContinue(
        StringBuilder sb, SoloJsIf iff, int depth, HashSet<string> declared, HashSet<string>? stateVars)
    {
        var pad = new string(' ', depth * 2);
        sb.Append("if (").Append(RewriteStateExpr(iff.Condition, stateVars)).AppendLine(") {");
        EmitBlock(sb, iff.ThenBody, depth + 1, declared, stateVars);
        sb.Append(pad).Append('}');
        if (iff.ElseBody.Count > 0)
        {
            if (iff.ElseBody is [SoloJsIf only])
            {
                sb.Append(" else ");
                EmitIfContinue(sb, only, depth, declared, stateVars);
            }
            else
            {
                sb.AppendLine(" else {");
                EmitBlock(sb, iff.ElseBody, depth + 1, declared, stateVars);
                sb.Append(pad).AppendLine("}");
            }
        }
        else sb.AppendLine();
    }

    private static string RewriteStateExpr(string expr, HashSet<string>? stateVars) => expr;

    private static string SetterName(string state) =>
        "set" + char.ToUpperInvariant(state[0]) + state[1..];

    private static string PropValue(string value) =>
        IsNumber(value) || value is "true" or "false" || IsIdent(value) ? value : JsString(value);

    private static bool IsIdent(string s) =>
        s.Length > 0 && (char.IsLetter(s[0]) || s[0] == '_') && s.All(ch => char.IsLetterOrDigit(ch) || ch == '_');

    private static bool IsNumber(string s) =>
        double.TryParse(s, System.Globalization.NumberStyles.Float,
            System.Globalization.CultureInfo.InvariantCulture, out _);

    private static string JsString(string s) =>
        "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private const string ReactPreamble = """
/* SoloJS React mode — expects React + ReactDOM globals (UMD or bundler). */
""";

    private const string Runtime = """
const solo = {
  $(sel) {
    return document.querySelector(sel);
  },
  on(sel, eventName, handler) {
    const el = this.$(sel);
    if (!el) { console.warn("SoloJS: no element for", sel); return; }
    el.addEventListener(eventName, handler);
  },
  set(sel, prop, value) {
    const el = this.$(sel);
    if (!el) { console.warn("SoloJS: no element for", sel); return; }
    if (prop === "text") el.textContent = value;
    else if (prop === "html") el.innerHTML = value;
    else if (prop === "value") el.value = value;
    else if (prop === "class") el.className = value;
    else el.setAttribute(prop, value);
  },
  fetch(url) {
    return fetch(url);
  },
  after(ms, handler) {
    return setTimeout(handler, Number(ms));
  },
  every(ms, handler) {
    return setInterval(handler, Number(ms));
  },
  react: {
    mount(Component, sel, props) {
      const el = document.querySelector(sel);
      if (!el) { console.warn("SoloJS React: no mount target", sel); return; }
      if (typeof React === "undefined" || typeof ReactDOM === "undefined") {
        console.error("SoloJS React: load React 18 UMD scripts first.");
        el.textContent = "React is not loaded. Add React + ReactDOM scripts.";
        return;
      }
      const root = ReactDOM.createRoot(el);
      root.render(React.createElement(Component, props || null));
      return root;
    }
  }
};
""";
}
