using System.Text;

namespace SoloRust.Compiler;

public sealed class RustEmitter
{
    public string Emit(SoloRustProgram program, string? crateName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by SoloRUST — SoloGem Solo5 (experimental)");
        sb.AppendLine("// Beginner-friendly Rust. Ownership advanced features come later.");
        if (!string.IsNullOrWhiteSpace(crateName))
            sb.Append("// crate: ").AppendLine(crateName);
        sb.AppendLine();

        foreach (var item in program.Items)
        {
            if (item is SoloRustFn fn)
                EmitFn(sb, fn);
        }

        return sb.ToString();
    }

    private static void EmitFn(StringBuilder sb, SoloRustFn fn)
    {
        sb.Append("fn ").Append(fn.Name).Append('(');
        sb.Append(string.Join(", ", fn.Params.Select(p => $"{p.Name}: {p.Type}")));
        sb.Append(')');
        if (fn.ReturnType is not null)
            sb.Append(" -> ").Append(fn.ReturnType);
        sb.AppendLine(" {");
        EmitStmts(sb, fn.Body, 1);
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitStmts(StringBuilder sb, List<SoloRustStmt> stmts, int depth)
    {
        var pad = new string(' ', depth * 4);
        foreach (var stmt in stmts)
        {
            switch (stmt)
            {
                case SoloRustComment c:
                    sb.Append(pad).Append("// ").AppendLine(c.Text);
                    break;

                case SoloRustLet let:
                    sb.Append(pad).Append(let.Mutable ? "let mut " : "let ").Append(let.Name);
                    if (let.Type is not null)
                        sb.Append(": ").Append(let.Type);
                    sb.Append(" = ").Append(RewriteExpr(let.Value)).AppendLine(";");
                    break;

                case SoloRustPrintln p:
                    sb.Append(pad).Append("println!(\"").Append(Escape(p.Template)).Append('"');
                    foreach (var arg in p.Args)
                        sb.Append(", ").Append(RewriteExpr(arg));
                    sb.AppendLine(");");
                    break;

                case SoloRustIf iff:
                    sb.Append(pad).Append("if ").Append(RewriteExpr(iff.Condition)).AppendLine(" {");
                    EmitStmts(sb, iff.ThenBody, depth + 1);
                    sb.Append(pad).Append('}');
                    if (iff.ElseBody.Count > 0)
                    {
                        sb.AppendLine(" else {");
                        EmitStmts(sb, iff.ElseBody, depth + 1);
                        sb.Append(pad).AppendLine("}");
                    }
                    else sb.AppendLine();
                    break;

                case SoloRustFor fr:
                    sb.Append(pad).Append("for ").Append(fr.Variable).Append(" in ")
                        .Append(fr.RangeStart).Append("..").Append(fr.RangeEnd).AppendLine(" {");
                    EmitStmts(sb, fr.Body, depth + 1);
                    sb.Append(pad).AppendLine("}");
                    break;

                case SoloRustWhile wh:
                    sb.Append(pad).Append("while ").Append(RewriteExpr(wh.Condition)).AppendLine(" {");
                    EmitStmts(sb, wh.Body, depth + 1);
                    sb.Append(pad).AppendLine("}");
                    break;

                case SoloRustReturn r:
                    sb.Append(pad).Append("return");
                    if (r.Value is not null)
                        sb.Append(' ').Append(RewriteExpr(r.Value));
                    sb.AppendLine(";");
                    break;

                case SoloRustExprStmt e:
                    sb.Append(pad).Append(RewriteExpr(e.Code)).AppendLine(";");
                    break;
            }
        }
    }

    private static string RewriteExpr(string expr)
    {
        // Allow and/or for beginners
        return expr
            .Replace(" and ", " && ", StringComparison.OrdinalIgnoreCase)
            .Replace(" or ", " || ", StringComparison.OrdinalIgnoreCase);
    }

    private static string Escape(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
