using System.Text;

namespace SoloRust.Compiler;

public sealed class RustEmitter
{
    public string Emit(SoloRustProgram program, string? crateName, bool borrowCoach = true)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by SoloRUST — SoloGem Solo5 (experimental)");
        sb.AppendLine("// Beginner-friendly Rust. Ownership advanced features come later.");
        if (borrowCoach)
            sb.AppendLine("// Borrow coach comments explain moves vs copies in plain language.");
        if (!string.IsNullOrWhiteSpace(crateName))
            sb.Append("// crate: ").AppendLine(crateName);
        sb.AppendLine();

        foreach (var item in program.Items)
        {
            if (item is SoloRustFn fn)
                EmitFn(sb, fn, borrowCoach);
        }

        return sb.ToString();
    }

    private static void EmitFn(StringBuilder sb, SoloRustFn fn, bool borrowCoach)
    {
        if (borrowCoach && fn.Name == "main")
            sb.AppendLine("// coach: `main` owns the program start — values created here live until dropped.");

        sb.Append("fn ").Append(fn.Name).Append('(');
        sb.Append(string.Join(", ", fn.Params.Select(p => $"{p.Name}: {p.Type}")));
        sb.Append(')');
        if (fn.ReturnType is not null)
            sb.Append(" -> ").Append(fn.ReturnType);
        sb.AppendLine(" {");
        EmitStmts(sb, fn.Body, 1, borrowCoach);
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitStmts(StringBuilder sb, List<SoloRustStmt> stmts, int depth, bool borrowCoach)
    {
        var pad = new string(' ', depth * 4);
        foreach (var stmt in stmts)
        {
            switch (stmt)
            {
                case SoloRustComment c:
                    sb.Append(pad).Append("// ").AppendLine(c.Text);
                    break;

                case SoloRustLet let:
                    if (borrowCoach)
                    {
                        if (let.Mutable)
                            sb.Append(pad).AppendLine("// coach: `mut` means this binding can change later (still one owner).");
                        else if (LooksLikeString(let.Value))
                            sb.Append(pad).AppendLine("// coach: this String-like value is owned here; passing it moves ownership unless you borrow.");
                        else
                            sb.Append(pad).AppendLine("// coach: simple numbers/bools usually Copy — using them doesn't move.");
                    }
                    sb.Append(pad).Append(let.Mutable ? "let mut " : "let ").Append(let.Name);
                    if (let.Type is not null)
                        sb.Append(": ").Append(let.Type);
                    sb.Append(" = ").Append(RewriteExpr(let.Value)).AppendLine(";");
                    break;

                case SoloRustPrintln p:
                    if (borrowCoach && p.Args.Count > 0)
                        sb.Append(pad).AppendLine("// coach: println! borrows its arguments for display — ownership usually stays put.");
                    sb.Append(pad).Append("println!(\"").Append(Escape(p.Template)).Append('"');
                    foreach (var arg in p.Args)
                        sb.Append(", ").Append(RewriteExpr(arg));
                    sb.AppendLine(");");
                    break;

                case SoloRustIf iff:
                    sb.Append(pad).Append("if ").Append(RewriteExpr(iff.Condition)).AppendLine(" {");
                    EmitStmts(sb, iff.ThenBody, depth + 1, borrowCoach);
                    sb.Append(pad).Append('}');
                    if (iff.ElseBody.Count > 0)
                    {
                        sb.AppendLine(" else {");
                        EmitStmts(sb, iff.ElseBody, depth + 1, borrowCoach);
                        sb.Append(pad).AppendLine("}");
                    }
                    else sb.AppendLine();
                    break;

                case SoloRustFor fr:
                    if (borrowCoach)
                        sb.Append(pad).AppendLine("// coach: `for` takes ownership of the iterator; `i` is a fresh binding each step.");
                    sb.Append(pad).Append("for ").Append(fr.Variable).Append(" in ")
                        .Append(fr.RangeStart).Append("..").Append(fr.RangeEnd).AppendLine(" {");
                    EmitStmts(sb, fr.Body, depth + 1, borrowCoach);
                    sb.Append(pad).AppendLine("}");
                    break;

                case SoloRustWhile wh:
                    sb.Append(pad).Append("while ").Append(RewriteExpr(wh.Condition)).AppendLine(" {");
                    EmitStmts(sb, wh.Body, depth + 1, borrowCoach);
                    sb.Append(pad).AppendLine("}");
                    break;

                case SoloRustReturn r:
                    if (borrowCoach && r.Value is not null)
                        sb.Append(pad).AppendLine("// coach: `return` moves the value out of this function to the caller.");
                    sb.Append(pad).Append("return");
                    if (r.Value is not null)
                        sb.Append(' ').Append(RewriteExpr(r.Value));
                    sb.AppendLine(";");
                    break;

                case SoloRustExprStmt e:
                    if (borrowCoach && e.Code.Contains('=') && !e.Code.Contains("=="))
                        sb.Append(pad).AppendLine("// coach: assignment reuses the same binding — still one owner.");
                    sb.Append(pad).Append(RewriteExpr(e.Code)).AppendLine(";");
                    break;
            }
        }
    }

    private static bool LooksLikeString(string expr)
    {
        var t = expr.Trim();
        return t.StartsWith('"') || t.StartsWith("String::", StringComparison.Ordinal);
    }

    private static string RewriteExpr(string expr)
    {
        return expr
            .Replace(" and ", " && ", StringComparison.OrdinalIgnoreCase)
            .Replace(" or ", " || ", StringComparison.OrdinalIgnoreCase);
    }

    private static string Escape(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
