<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SoloLua.Cli</RootNamespace>
    <AssemblyName>sololua</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SoloLua.Compiler\SoloLua.Compiler.csproj" />
  </ItemGroup>
</Project>
