<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SoloJs.Cli</RootNamespace>
    <AssemblyName>solojs</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SoloJs.Compiler\SoloJs.Compiler.csproj" />
  </ItemGroup>
</Project>
