<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SoloRust.Cli</RootNamespace>
    <AssemblyName>solorust</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SoloRust.Compiler\SoloRust.Compiler.csproj" />
  </ItemGroup>
</Project>
