using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace SoloPage.Compiler;

/// <summary>
/// Build-time data → pages from JSON + SoloHTML templates ({{slug}} etc.).
/// </summary>
public static class SoloPageData
{
    public static List<GeneratedPage> ExpandCollections(string projectDir, SiteConfig? config)
    {
        var results = new List<GeneratedPage>();
        if (config?.Collections is null || config.Collections.Count == 0)
            return results;

        foreach (var col in config.Collections)
        {
            var dataPath = Path.Combine(projectDir, col.Data.Replace('/', Path.DirectorySeparatorChar));
            var templatePath = Path.Combine(projectDir, col.Template.Replace('/', Path.DirectorySeparatorChar));
            if (!File.Exists(dataPath))
                throw new InvalidOperationException($"Collection data not found: {col.Data}");
            if (!File.Exists(templatePath))
                throw new InvalidOperationException($"Collection template not found: {col.Template}");

            var template = File.ReadAllText(templatePath);
            using var doc = JsonDocument.Parse(File.ReadAllText(dataPath));
            if (doc.RootElement.ValueKind != JsonValueKind.Array)
                throw new InvalidOperationException($"Collection data must be a JSON array: {col.Data}");

            foreach (var item in doc.RootElement.EnumerateArray())
            {
                var map = FlattenJson(item);
                if (!map.ContainsKey("slug") && map.ContainsKey("id"))
                    map["slug"] = map["id"];
                if (!map.TryGetValue("slug", out var slug) || string.IsNullOrWhiteSpace(slug))
                    throw new InvalidOperationException($"Collection item in {col.Data} needs a slug (or id)");

                var source = Substitute(template, map);
                var outRel = Substitute(col.Out ?? "{{slug}}/index.html", map)
                    .Replace('\\', '/')
                    .TrimStart('/');
                var route = Substitute(col.Route ?? "/" + Path.GetDirectoryName(outRel)!.Replace('\\', '/'), map);
                if (!route.StartsWith('/'))
                    route = "/" + route;
                route = route.TrimEnd('/');
                if (route.Length == 0) route = "/";

                results.Add(new GeneratedPage(source, route, outRel, Path.GetDirectoryName(templatePath)!));
            }
        }

        return results;
    }

    public static SiteConfig? LoadConfig(string projectDir)
    {
        foreach (var name in new[] { "site.json", "site.solo5.json", "solopage.json" })
        {
            var path = Path.Combine(projectDir, name);
            if (!File.Exists(path))
                continue;
            var json = File.ReadAllText(path);
            return JsonSerializer.Deserialize<SiteConfig>(json, new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true,
                ReadCommentHandling = JsonCommentHandling.Skip,
                AllowTrailingCommas = true,
            });
        }
        return null;
    }

    public static string BuildRedirects(IEnumerable<string> routes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by SoloPage — Netlify clean URLs");
        foreach (var route in routes.Distinct().OrderBy(r => r))
        {
            if (route is "/" or "")
                continue;
            var pretty = route.TrimEnd('/');
            sb.Append(pretty).Append("  ").Append(pretty).AppendLine("/  301");
        }
        return sb.ToString();
    }

    public static string BuildSitemap(string baseUrl, IEnumerable<string> routes)
    {
        baseUrl = baseUrl.TrimEnd('/');
        var sb = new StringBuilder();
        sb.AppendLine("""<?xml version="1.0" encoding="UTF-8"?>""");
        sb.AppendLine("""<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">""");
        foreach (var route in routes.Distinct().OrderBy(r => r))
        {
            var loc = route is "/" or "" ? baseUrl + "/" : baseUrl + route.TrimEnd('/') + "/";
            sb.Append("  <url><loc>").Append(System.Net.WebUtility.HtmlEncode(loc)).AppendLine("</loc></url>");
        }
        sb.AppendLine("</urlset>");
        return sb.ToString();
    }

    public static string BuildRobots(string baseUrl)
    {
        baseUrl = baseUrl.TrimEnd('/');
        return $"User-agent: *\nAllow: /\nSitemap: {baseUrl}/sitemap.xml\n";
    }

    private static Dictionary<string, string> FlattenJson(JsonElement el, string prefix = "")
    {
        var map = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        if (el.ValueKind != JsonValueKind.Object)
            return map;

        foreach (var prop in el.EnumerateObject())
        {
            var key = string.IsNullOrEmpty(prefix) ? prop.Name : prefix + "." + prop.Name;
            switch (prop.Value.ValueKind)
            {
                case JsonValueKind.String:
                    map[key] = prop.Value.GetString() ?? "";
                    break;
                case JsonValueKind.Number:
                case JsonValueKind.True:
                case JsonValueKind.False:
                    map[key] = prop.Value.ToString();
                    break;
                case JsonValueKind.Object:
                    foreach (var (k, v) in FlattenJson(prop.Value, key))
                        map[k] = v;
                    break;
                case JsonValueKind.Array:
                    map[key] = prop.Value.GetRawText();
                    break;
            }
        }
        return map;
    }

    private static string Substitute(string template, IReadOnlyDictionary<string, string> map) =>
        Regex.Replace(template, @"\{\{\s*([A-Za-z0-9_.-]+)\s*\}\}", m =>
            map.TryGetValue(m.Groups[1].Value, out var v) ? v : m.Value);
}

public sealed class SiteConfig
{
    public string? BaseUrl { get; set; }
    public List<SiteCollection> Collections { get; set; } = [];
    public bool GenerateRedirects { get; set; } = true;
    public bool GenerateSitemap { get; set; } = true;
    public bool GenerateRobots { get; set; } = true;
}

public sealed class SiteCollection
{
    public string Data { get; set; } = "";
    public string Template { get; set; } = "";
    public string? Out { get; set; }
    public string? Route { get; set; }
}

public sealed record GeneratedPage(string Source, string Route, string OutRelativePath, string BasePath);
