<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>solopage</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SoloPage.Compiler\SoloPage.Compiler.csproj" />
  </ItemGroup>
</Project>
