using System.Text;

namespace SoloLua.Compiler;

public sealed class LuaEmitter
{
    private int _contId;

    public string Emit(SoloLuaProgram program, string? title = null)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- Generated by SoloLua — SoloGem Solo5");
        sb.AppendLine("-- Lua 5.4 / LuaJIT-friendly. Locals by default; lists are dense.");
        if (!string.IsNullOrWhiteSpace(title))
            sb.Append("-- ").AppendLine(title);
        sb.AppendLine();
        sb.AppendLine(Runtime);
        sb.AppendLine();
        EmitBlock(sb, program.Body, 0, new HashSet<string>(StringComparer.Ordinal), loopContinue: null);
        return sb.ToString();
    }

    private void EmitBlock(
        StringBuilder sb,
        List<SoloLuaNode> nodes,
        int depth,
        HashSet<string> declared,
        string? loopContinue)
    {
        var pad = new string(' ', depth * 2);
        foreach (var node in nodes)
            EmitNode(sb, node, depth, pad, declared, loopContinue);
    }

    private void EmitNode(
        StringBuilder sb,
        SoloLuaNode node,
        int depth,
        string pad,
        HashSet<string> declared,
        string? loopContinue)
    {
        switch (node)
        {
            case SoloLuaComment c:
                sb.Append(pad).Append("-- ").AppendLine(c.Text);
                break;

            case SoloLuaImport imp:
            {
                var alias = imp.Alias ?? PathAlias(imp.Module);
                DeclareLocal(sb, pad, alias, declared);
                sb.Append(pad).Append(alias).Append(" = assert(require(")
                    .Append(LuaString(imp.Module)).AppendLine("))");
                break;
            }

            case SoloLuaClass cls:
                EmitClass(sb, cls, depth, pad, declared);
                break;

            case SoloLuaFn fn:
                EmitFn(sb, fn, depth, pad, declared, asMethod: false);
                break;

            case SoloLuaIf iff:
                EmitIf(sb, iff, depth, pad, declared, loopContinue);
                break;

            case SoloLuaWhile wh:
            {
                var cont = NextContinue();
                sb.Append(pad).Append("while ").Append(ExprRewrite.Rewrite(wh.Condition)).AppendLine(" do");
                EmitBlock(sb, wh.Body, depth + 1, declared, cont);
                sb.Append(pad).Append("  ::").Append(cont).AppendLine("::");
                sb.Append(pad).AppendLine("end");
                break;
            }

            case SoloLuaForRange fr:
            {
                var cont = NextContinue();
                // SoloLua ranges are inclusive start..end like Lua numeric for when end is inclusive.
                // `for i in 1..3` → for i = 1, 3 do  (Lua end is inclusive)
                sb.Append(pad).Append("for ").Append(fr.Variable).Append(" = ")
                    .Append(ExprRewrite.Rewrite(fr.Start)).Append(", ")
                    .Append(ExprRewrite.Rewrite(fr.End)).AppendLine(" do");
                var scope = new HashSet<string>(declared, StringComparer.Ordinal) { fr.Variable };
                EmitBlock(sb, fr.Body, depth + 1, scope, cont);
                sb.Append(pad).Append("  ::").Append(cont).AppendLine("::");
                sb.Append(pad).AppendLine("end");
                break;
            }

            case SoloLuaForEach fe:
            {
                var cont = NextContinue();
                var iter = ExprRewrite.Rewrite(fe.Iterable);
                if (fe.Key is not null)
                {
                    sb.Append(pad).Append("for ").Append(fe.Key).Append(", ").Append(fe.Value)
                        .Append(" in solo.pairs(").Append(iter).AppendLine(") do");
                    var scope = new HashSet<string>(declared, StringComparer.Ordinal) { fe.Key, fe.Value };
                    EmitBlock(sb, fe.Body, depth + 1, scope, cont);
                }
                else
                {
                    sb.Append(pad).Append("for _, ").Append(fe.Value)
                        .Append(" in solo.ipairs(").Append(iter).AppendLine(") do");
                    var scope = new HashSet<string>(declared, StringComparer.Ordinal) { fe.Value };
                    EmitBlock(sb, fe.Body, depth + 1, scope, cont);
                }
                sb.Append(pad).Append("  ::").Append(cont).AppendLine("::");
                sb.Append(pad).AppendLine("end");
                break;
            }

            case SoloLuaTry tr:
            {
                sb.Append(pad).AppendLine("do");
                sb.Append(pad).Append("  local __ok, __res = solo.try(function()");
                sb.AppendLine();
                EmitBlock(sb, tr.TryBody, depth + 2, new HashSet<string>(declared, StringComparer.Ordinal), loopContinue);
                sb.Append(pad).AppendLine("  end)");
                sb.Append(pad).AppendLine("  if not __ok then");
                sb.Append(pad).Append("    local ").Append(tr.CatchName).AppendLine(" = __res");
                EmitBlock(sb, tr.CatchBody, depth + 2, new HashSet<string>(declared, StringComparer.Ordinal) { tr.CatchName }, loopContinue);
                sb.Append(pad).AppendLine("  end");
                sb.Append(pad).AppendLine("end");
                break;
            }

            case SoloLuaPrint p:
                if (string.IsNullOrWhiteSpace(p.Args))
                    sb.Append(pad).AppendLine("print()");
                else
                    sb.Append(pad).Append("print(").Append(ExprRewrite.Rewrite(p.Args)).AppendLine(")");
                break;

            case SoloLuaReturn r:
                if (r.Value is null)
                    sb.Append(pad).AppendLine("return");
                else
                    sb.Append(pad).Append("return ").Append(ExprRewrite.Rewrite(r.Value)).AppendLine();
                break;

            case SoloLuaContinue:
                if (loopContinue is null)
                    throw new SoloLuaException($"line {node.Line}: `continue` outside a loop");
                sb.Append(pad).Append("goto ").Append(loopContinue).AppendLine();
                break;

            case SoloLuaBreak:
                sb.Append(pad).AppendLine("break");
                break;

            case SoloLuaListLiteral list:
                EmitBinding(sb, pad, list.Name, list.IsGlobal, declared,
                    $"solo.list({ExprRewrite.Rewrite(list.Items)})");
                break;

            case SoloLuaMapLiteral map:
            {
                var entries = string.Join(", ", map.Entries.Select(e =>
                {
                    var key = e.Key.StartsWith('"') || e.Key.StartsWith('\'')
                        ? $"[{e.Key}]"
                        : e.Key;
                    return $"{key} = {ExprRewrite.Rewrite(e.Value)}";
                }));
                EmitBinding(sb, pad, map.Name, map.IsGlobal, declared, $"solo.map({{ {entries} }})");
                break;
            }

            case SoloLuaAssign a:
                EmitAssign(sb, pad, a, declared);
                break;

            case SoloLuaExpr e:
                sb.Append(pad).Append(ExprRewrite.Rewrite(e.Code)).AppendLine();
                break;
        }
    }

    private void EmitIf(
        StringBuilder sb,
        SoloLuaIf iff,
        int depth,
        string pad,
        HashSet<string> declared,
        string? loopContinue)
    {
        sb.Append(pad).Append("if ").Append(ExprRewrite.Rewrite(iff.Condition)).AppendLine(" then");
        EmitBlock(sb, iff.ThenBody, depth + 1, declared, loopContinue);
        if (iff.ElseBody.Count > 0)
        {
            if (iff.ElseBody is [SoloLuaIf only])
            {
                sb.Append(pad).Append("elseif ").Append(ExprRewrite.Rewrite(only.Condition)).AppendLine(" then");
                EmitBlock(sb, only.ThenBody, depth + 1, declared, loopContinue);
                EmitElseTail(sb, only.ElseBody, depth, pad, declared, loopContinue);
            }
            else
            {
                sb.Append(pad).AppendLine("else");
                EmitBlock(sb, iff.ElseBody, depth + 1, declared, loopContinue);
            }
        }
        sb.Append(pad).AppendLine("end");
    }

    private void EmitElseTail(
        StringBuilder sb,
        List<SoloLuaNode> elseBody,
        int depth,
        string pad,
        HashSet<string> declared,
        string? loopContinue)
    {
        if (elseBody.Count == 0) return;
        if (elseBody is [SoloLuaIf only])
        {
            sb.Append(pad).Append("elseif ").Append(ExprRewrite.Rewrite(only.Condition)).AppendLine(" then");
            EmitBlock(sb, only.ThenBody, depth + 1, declared, loopContinue);
            EmitElseTail(sb, only.ElseBody, depth, pad, declared, loopContinue);
            return;
        }
        sb.Append(pad).AppendLine("else");
        EmitBlock(sb, elseBody, depth + 1, declared, loopContinue);
    }

    private void EmitFn(
        StringBuilder sb,
        SoloLuaFn fn,
        int depth,
        string pad,
        HashSet<string> declared,
        bool asMethod)
    {
        if (!asMethod)
            DeclareLocal(sb, pad, fn.Name, declared);

        var parms = asMethod
            ? string.Join(", ", new[] { "self" }.Concat(fn.Params))
            : string.Join(", ", fn.Params);

        sb.Append(pad).Append(fn.Name).Append(" = function(").Append(parms).AppendLine(")");
        var scope = new HashSet<string>(fn.Params, StringComparer.Ordinal);
        if (asMethod) scope.Add("self");
        EmitBlock(sb, fn.Body, depth + 1, scope, loopContinue: null);
        sb.Append(pad).AppendLine("end");
        if (!asMethod)
            sb.AppendLine();
    }

    private void EmitClass(StringBuilder sb, SoloLuaClass cls, int depth, string pad, HashSet<string> declared)
    {
        DeclareLocal(sb, pad, cls.Name, declared);
        sb.Append(pad).Append(cls.Name).AppendLine(" = solo.class({");
        var methods = cls.Body.OfType<SoloLuaFn>().ToList();
        for (var i = 0; i < methods.Count; i++)
        {
            var m = methods[i];
            var comma = i < methods.Count - 1 ? "," : "";
            var parms = string.Join(", ", new[] { "self" }.Concat(m.Params));
            sb.Append(pad).Append("  ").Append(m.Name).Append(" = function(").Append(parms).AppendLine(")");
            var scope = new HashSet<string>(m.Params, StringComparer.Ordinal) { "self" };
            EmitBlock(sb, m.Body, depth + 2, scope, null);
            sb.Append(pad).Append("  end").AppendLine(comma);
        }
        // non-fn body nodes as comments
        foreach (var other in cls.Body.Where(n => n is not SoloLuaFn and not SoloLuaComment))
            sb.Append(pad).Append("  -- skipped non-method in class: line ").Append(other.Line).AppendLine();
        sb.Append(pad).AppendLine("})");
        sb.AppendLine();
    }

    private static void EmitAssign(StringBuilder sb, string pad, SoloLuaAssign a, HashSet<string> declared)
    {
        var value = ExprRewrite.Rewrite(a.Value);
        if (a.Op is null)
        {
            EmitBinding(sb, pad, a.Name, a.IsGlobal, declared, value);
            return;
        }

        // compound: x += 1
        if (a.IsGlobal || a.Name.Contains('.') || a.Name.Contains('['))
        {
            // no local keyword
        }
        else if (!declared.Contains(a.Name))
            throw new SoloLuaException($"line {a.Line}: `{a.Op}` on undeclared `{a.Name}` — assign it first");

        var op = a.Op switch
        {
            "+=" => "+",
            "-=" => "-",
            "*=" => "*",
            "/=" => "/",
            "..=" => "..",
            _ => throw new SoloLuaException($"line {a.Line}: unknown operator {a.Op}"),
        };
        sb.Append(pad).Append(a.Name).Append(" = ").Append(a.Name).Append(' ').Append(op)
            .Append(' ').Append(value).AppendLine();
    }

    private static void EmitBinding(
        StringBuilder sb,
        string pad,
        string name,
        bool isGlobal,
        HashSet<string> declared,
        string valueExpr)
    {
        if (isGlobal)
        {
            sb.Append(pad).Append("_G.").Append(SimpleName(name)).Append(" = ").Append(valueExpr).AppendLine();
            return;
        }

        if (name.Contains('.') || name.Contains('['))
        {
            sb.Append(pad).Append(name).Append(" = ").Append(valueExpr).AppendLine();
            return;
        }

        if (!declared.Contains(name))
        {
            sb.Append(pad).Append("local ").Append(name).Append(" = ").Append(valueExpr).AppendLine();
            declared.Add(name);
        }
        else
        {
            sb.Append(pad).Append(name).Append(" = ").Append(valueExpr).AppendLine();
        }
    }

    private static void DeclareLocal(StringBuilder sb, string pad, string name, HashSet<string> declared)
    {
        if (declared.Contains(name)) return;
        sb.Append(pad).Append("local ").Append(name).AppendLine();
        declared.Add(name);
    }

    private string NextContinue() => $"__solo_cont_{++_contId}";

    private static string PathAlias(string module)
    {
        var leaf = module.Replace('\\', '/').Split('/').Last();
        leaf = Path.GetFileNameWithoutExtension(leaf);
        var cleaned = new string(leaf.Select(ch => char.IsLetterOrDigit(ch) ? ch : '_').ToArray());
        if (cleaned.Length == 0 || char.IsDigit(cleaned[0]))
            cleaned = "mod_" + cleaned;
        return cleaned;
    }

    private static string SimpleName(string name) =>
        name.Contains('.') ? name.Split('.').Last() : name;

    private static string LuaString(string s) =>
        "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private const string Runtime =
        """
        local solo = rawget(_G, "solo") or {}
        _G.solo = solo

        function solo.nullish(a, b)
          if a == nil then return b end
          return a
        end

        function solo.opt(obj, key)
          if obj == nil then return nil end
          return obj[key]
        end

        function solo.list(...)
          local t = { ... }
          local mt = {
            __index = {
              push = function(self, v)
                if v == nil then
                  error("solo.list: refusing to push nil (Lua array holes)", 2)
                end
                self[#self + 1] = v
                return self
              end,
              pop = function(self)
                local n = #self
                local v = self[n]
                self[n] = nil
                return v
              end,
              len = function(self) return #self end,
              at0 = function(self, i)
                return self[i + 1]
              end,
              set0 = function(self, i, v)
                if v == nil then
                  error("solo.list: refusing nil write (array holes)", 2)
                end
                self[i + 1] = v
                return self
              end,
              each = function(self, fn)
                for i = 1, #self do fn(self[i], i) end
                return self
              end,
            }
          }
          return setmetatable(t, mt)
        end

        function solo.map(t)
          t = t or {}
          local mt = {
            __index = {
              get = function(self, k) return rawget(self, k) end,
              set = function(self, k, v) rawset(self, k, v); return self end,
              has = function(self, k) return rawget(self, k) ~= nil end,
              keys = function(self)
                local ks = solo.list()
                for k, _ in pairs(self) do ks:push(k) end
                return ks
              end,
            }
          }
          return setmetatable(t, mt)
        end

        function solo.class(methods)
          methods = methods or {}
          local class = {}
          class.__index = class
          for k, v in pairs(methods) do
            if k ~= "new" then class[k] = v end
          end
          function class.new(...)
            local self = setmetatable({}, class)
            if type(methods.new) == "function" then
              return methods.new(self, ...) or self
            end
            return self
          end
          return class
        end

        function solo.try(fn)
          return pcall(fn)
        end

        function solo.ipairs(t)
          return ipairs(t)
        end

        function solo.pairs(t)
          return pairs(t)
        end
        """;
}
