using System.Text;

namespace SoloCss.Compiler;

public sealed class CssEmitter
{
    public string Emit(SoloCssDocument document)
    {
        var sb = new StringBuilder();
        sb.AppendLine("/* Generated by SoloCSS — SoloGem Solo5 */");
        sb.AppendLine();

        if (document.Vars.Count > 0)
        {
            sb.AppendLine(":root {");
            foreach (var (name, value) in document.Vars)
            {
                var resolved = ResolveVars(value, document.Vars);
                sb.Append("  --").Append(ToCssIdent(name)).Append(": ").Append(resolved).AppendLine(";");
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }

        foreach (var block in document.Blocks)
        {
            switch (block)
            {
                case SoloCssRule rule:
                    EmitRule(sb, rule, parentSelector: null, document.Vars);
                    break;
                case SoloCssMedia media:
                    sb.Append("@media ").Append(media.Query).AppendLine(" {");
                    foreach (var rule in media.Rules)
                        EmitRule(sb, rule, parentSelector: null, document.Vars, indent: "  ");
                    sb.AppendLine("}");
                    sb.AppendLine();
                    break;
            }
        }

        return sb.ToString().TrimEnd() + Environment.NewLine;
    }

    private static void EmitRule(
        StringBuilder sb,
        SoloCssRule rule,
        string? parentSelector,
        IReadOnlyDictionary<string, string> vars,
        string indent = "")
    {
        var selector = CombineSelector(parentSelector, rule.Selector);

        if (rule.Declarations.Count > 0)
        {
            sb.Append(indent).Append(selector).AppendLine(" {");
            foreach (var (prop, value) in rule.Declarations)
            {
                var (cssName, forced) = PropertyMap.Expand(prop, value);
                var rawValue = forced ?? value;
                // Prefer CSS custom properties: $brand → var(--brand)
                var resolved = ToCustomProps(rawValue, vars);
                sb.Append(indent).Append("  ").Append(cssName).Append(": ").Append(resolved).AppendLine(";");
            }
            sb.Append(indent).AppendLine("}");
            sb.AppendLine();
        }

        foreach (var child in rule.Children)
            EmitRule(sb, child, selector, vars, indent);
    }

    private static string CombineSelector(string? parent, string child)
    {
        child = child.Trim();
        if (string.IsNullOrEmpty(parent))
            return child;

        // & means parent reference
        if (child.StartsWith('&'))
            return parent + child[1..];

        // Nested selectors: parent child (descendant)
        // If child starts with : or . or # attached intent — still descendant unless &
        return parent + " " + child;
    }

    private static string ResolveVars(string value, IReadOnlyDictionary<string, string> vars)
    {
        var result = value;
        foreach (var (name, val) in vars.OrderByDescending(kv => kv.Key.Length))
            result = ReplaceIgnoreCase(result, "$" + name, val);
        return result;
    }

    private static string ToCustomProps(string value, IReadOnlyDictionary<string, string> vars)
    {
        var result = value;
        foreach (var name in vars.Keys.OrderByDescending(k => k.Length))
            result = ReplaceIgnoreCase(result, "$" + name, $"var(--{ToCssIdent(name)})");
        // Also rewrite unknown $tokens to var(--token) for forward-compat
        result = System.Text.RegularExpressions.Regex.Replace(
            result,
            @"\$([A-Za-z_][\w-]*)",
            m => $"var(--{ToCssIdent(m.Groups[1].Value)})");
        return result;
    }

    private static string ReplaceIgnoreCase(string input, string oldValue, string newValue)
    {
        var sb = new StringBuilder();
        var i = 0;
        while (i < input.Length)
        {
            if (i + oldValue.Length <= input.Length &&
                string.Compare(input, i, oldValue, 0, oldValue.Length, StringComparison.OrdinalIgnoreCase) == 0)
            {
                // Don't replace mid-identifier after $
                sb.Append(newValue);
                i += oldValue.Length;
            }
            else
            {
                sb.Append(input[i]);
                i++;
            }
        }
        return sb.ToString();
    }

    private static string ToCssIdent(string name) =>
        string.Concat(name.Select(ch => char.IsLetterOrDigit(ch) ? char.ToLowerInvariant(ch) : '-'));
}
